#!/bin/bash
# Allow aliases to be with sudo
alias sudo="sudo "

# Easier navigation: .., ..., ~ and /
alias ..="cd .."
alias ..2="cd ../.."
alias ..3="cd ../../.."
alias ..4="cd ../../../.."
alias dev="cd ~/Documents/dev"
alias ~="cd ~"

alias reset="clear && printf '\e[3J'"

alias mkdir="mkdir -pv"

function ls () {
    realpath "${@:-"."}"
    /bin/ls -AFGh "${@:-"."}"
}
function lsl () {
    realpath "${@:-"."}"
    /bin/ls -AFGhl "${@:-"."}"
}

# Continue getting a partially-downloaded file.
alias wget='wget -c'

# Copy my public key to the pasteboard
alias pubkey="more ~/.ssh/id_rsa.pub | pbcopy | printf '=> Public key copied to pasteboard.\n'"

# Hide/show all desktop icons (useful when presenting)
alias showdeskicons="defaults write com.apple.finder CreateDesktop -bool true && killall Finder"
alias hidedeskicons="defaults write com.apple.finder CreateDesktop -bool false && killall Finder"

# Sublime to be used to open files and folders
alias sublime="/Applications/Sublime\ Text.app/Contents/SharedSupport/bin/subl"

# Use hub instead of git
alias git=hub

# Default to python3
alias python="python3"

alias start="gcloud compute instances start"
alias stop="gcloud compute instances stop"
alias gssh="gcloud compute ssh"

alias code="code-insiders"