source ${HOME}/novus.mac/shell/aliases
source ${HOME}/novus.mac/shell/exports
source ${HOME}/novus.mac/shell/paths

for function in ${HOME}/novus.mac/shell/functions/*; do
  source $function
done

parse_git_branch() {    
  git name-rev HEAD 2> /dev/null | sed 's#HEAD\ \(.*\)# (\1)#'
}

export PS1="\w\[\033[32m\]\$(parse_git_branch)\[\033[0m\] ✗ "

# Autocorrect typos in path names when using `cd`
shopt -s cdspell

# Check the window size after each command and, if necessary, update the values
# of LINES and COLUMNS.
shopt -s checkwinsize

# Append to the Bash history file, rather than overwriting it
shopt -s histappend

# Case-insensitive globbing (used in pathname expansion)
shopt -s nocaseglob

source ${HOME}/novus.mac/shell/.bash_nvidia

source ~/libs/git-completion.bash
