#!/bin/bash

run_brew() {
  # Check for Homebrew
  if cmd_exists 'brew'; then
    log_header "Updating Homebrew..."
    # Use the latest version of Homebrew
    brew update && log_success "Done"

    log_header "Updating existing Homebrew formulae..."
    brew upgrade && log_success "Done"

    declare -a formulae=("go" "cmake" "wget" "tree" "zsh" "zsh-completions"
                         "macvim --override-system-vim" "git-flow")

    ## now loop through the above array
    for i in "${arr[@]}"
    do
       echo "$i"
       # or do whatever with individual element of the array
    done

    # Remove outdated versions from the Cellar
    brew cleanup
  else
    log_error "Error: Homebrew not found."
  fi
}