#!/bin/bash

source ./lib/logging
source ./lib/brew
source ./lib/node

# Test whether a command "$1" exists
cmd_exists() {
  if [ $(type -P $1) ]; then
  true
  else
  false
  fi
}

run_help() {
  log_header "  novus.mac"
  cat <<EOT
  Author: Anmol Mago (http://anmolmago.com)
  Usage: $(basename "$0") [command]
  Commands:
  install    Install all settings and applications
  -h, --help, help   Print this help text
  -l, --list, list   Print a list of what will be installed
  Copyright (c) Anmol Mago
  Licensed under the MIT license.
EOT
}

is_git_repo() {
  $(git rev-parse --is-inside-work-tree &> /dev/null)
}

novus_link() {
  # Force create/replace the symlink.
  ln -fs "${DOTFILES_DIRECTORY}/${1}" "${HOME}/${2}"
}

install_brew_packages() {
  
}
