#!/bin/bash

source ./lib/logging

# Test whether a command "$1" exists
cmd_exists() {
  if [ $(type -P $1) ]; then
  true
  else
  false
fi
}

confirm() {
  read -p "${1}? [y/N]" response
  case "$response" in
    [yY][eE][sS]|[yY]) 
      true
      ;;
    *)
      false
      ;;
  esac
}

run_help() {
  log_header "  novus.mac"
  cat <<EOT
  Author: Anmol Mago (http://anmolmago.com)
  Usage: $(basename "$0") [command]
  Commands:
  install    Install all settings and applications
  -h, --help, help   Print this help text
  Copyright (c) Anmol Mago
  Licensed under the MIT license.
EOT
}

is_git_repo() {
  $(git rev-parse --is-inside-work-tree &> /dev/null)
}

novus_link() {
  # Force create/replace the symlink.
  ln -fs "${HOME}/novus.mac/${1}" "${HOME}/${2}"
}

prompt() {
  read -p "${1}. Press enter to continue."
}
